### ISSUE TITLE
Uninstall 

### ISSUE THREAD

**Issue by Atharv-Pathak-14** [Sohil876/Termux-zsh#3]
How to uninstall it

**Comment by Sohil876** [comment]
I haven't wrote a uninstaller yet but its very easy.

To do a complete uninstall just enter this in termux (This will remove all zsh, ohmyzsh and termux-zsh related stuff!)
`chsh -s bash && rm -rf ~/.termux ~/.zshrc ~/.oh-my-zsh ~/.p10k.zsh ~/.zcompdump-localhost*`

Then just restart termux.
