### ISSUE TITLE
Request for Customizable Prompt with Specific Format

### ISSUE THREAD

**Issue by sb-codz** [Sohil876/Termux-zsh#6]
Hi, I'm using Powerlevel10k for my Zsh configuration, and I'd like to request a customization for the prompt format. Specifically, I want to replicate the following prompt structure:

╭─user@hostname
├─~/path/to/directory
╰─❯

Desired Features:

The first line should show ╭─user@hostname.

The second line should show ├─~/path/to/directory.

The third line should show ╰─❯ as the prompt character.

Context:

I’m looking for a way to modify the prompt such that:

1. The user and hostname are displayed on the first line with ╭─ prefix.

2. The directory path is displayed on the second line with ├─ prefix.

3. The prompt character is displayed on the third line, ╰─❯.

Expected Outcome:

An option to configure the Powerlevel10k prompt in this specific structure, or guidance on how I can achieve this customization manually.

**Comment by Sohil876** [comment]
The purpose of this repository is to provide a specific setup for termux, if you are looking to customize powerlevel10k theme follow their documentation in their readme https://github.com/romkatv/powerlevel10k

I have not really been customizing my custom p10k theme for quite some time as i have it just like i want to, i don't really remember much hence it would be better if you just refer to their documentation, iirc there's a .p10k.zsh in your home directory and you configure this there.

You can also try if you can have your desired outcome with their configuration wizard by command
`p10k configure`
